### ISSUE TITLE
Create API endpoint for single location

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#234]
## Description
Develop an API endpoint that retrieves information about a single location. The endpoint should handle requests for data from one or more datasets. The exact specifications for what data needs to be returned are currently unclear and need clarification.

## Acceptance criteria
* API endpoint is able to fetch and return data for a specified location.
* Supports queries for multiple datasets simultaneously.
* Proper validation and error handling are implemented.

## Tasks
- [ ] Clarify requirements with all teams.
- [ ] Design the API endpoint structure.
- [ ] Implement the endpoint.
- [ ] Test the API to ensure it meets the functional requirements.

## Definition of done (DoD)
* Component tests have been written and pass 
* All CI tests passed for the pull request 
* Code review has been completed and code has been merged into sprint-release branch 
* All feature branches have been merged and closed 
* New feature code has been documented

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release
