### ISSUE TITLE
Add argument to data pipeline to overwrite if_table_exists option

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#235]
## Description
Modify the data pipeline script to include an option that allows overwriting existing tables if specified.

## Acceptance criteria
* Data pipeline script includes a configurable parameter to overwrite tables.

## Tasks
- [ ] Update the data pipeline code to accept a new parameter for table overwriting.
- [ ] Implement changes in the pipeline configuration.
- [ ] Test the updated pipeline script.

## Definition of done (DoD)
* Component tests have been written and pass 
* All CI tests passed for the pull request 
* Code review has been completed and code has been merged into sprint-release branch 
* All feature branches have been merged and closed 
* New feature code has been documented

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release
