### ISSUE TITLE
Create script to run datapipeline for each dataset upon deployment

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#236]
## Description
 Develop a script that automatically triggers the data pipeline for each dataset upon system deployment.

## Acceptance criteria
*  Script executes data pipeline runs for all datasets during the deployment process.
* Successful execution logs and data validation post-deployment.

## Tasks
- [ ] Write a deployment script that initiates the data pipeline.
- [ ] Integrate the script with the deployment process.
- [ ] Validate and document the deployment and data ingestion process.

## Definition of done (DoD)
* Component tests have been written and pass 
* All CI tests passed for the pull request 
* Code review has been completed and code has been merged into sprint-release branch 
* All feature branches have been merged and closed 
* New feature code has been documented

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release
