### ISSUE TITLE
Clean up data pipeline

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#237]
## Description
Implement basic exception handling in the data pipeline to enhance stability and reliability. 

## Acceptance criteria
* Exception handling mechanisms are in place throughout the data pipeline.
* All known errors are gracefully handled, and appropriate logs are generated.

## Tasks
- [ ] Review the existing pipeline for error handling gaps.
- [ ] Design and implement comprehensive exception handling.
- [ ] Test error handling under various failure scenarios.

## Definition of done (DoD)
* Component tests have been written and pass 
* All CI tests passed for the pull request 
* Code review has been completed and code has been merged into sprint-release branch 
* All feature branches have been merged and closed 
* New feature code has been documented

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release
