### ISSUE TITLE
Team Logo and Tshirt

### ISSUE THREAD

**Issue by op-hub** [amosproj/amos2024ss04-building-information-enhancer#5]
## Task specs
- [x] #7 
- [x] Link to design in planning document
- [x] Upload to deliverables as svg / png
- [x] submit individual preferences

## Deadline
- Ideal: Wednesday 24.04
- (Optinal on week later till Wednesday 01.05) 

## Blockers
*
