### ISSUE TITLE
Update GitHub README.md

### ISSUE THREAD

**Issue by dancingsushii** [amosproj/amos2024ss04-building-information-enhancer#85]
## Task specs
We are asked to update our GitHub README.md. Please, check that all important information is specified, e.g.

- [x] Our logo is visible
- [x] Labels with brief info is present (see screenshot below)
- [x] Short "About the project" or "Abstract" is listed on top
- [x] Prerequisites are listed (C#, node, React, Docker etc)
- [x] "Getting Started" manual is written
- [x] Product mission is stated
- [x] Product vision is stated
- [x] Contributors are mentioned

![Image](https://github.com/amosproj/amos2024ss04-building-information-enhancer/assets/46463790/4881c929-6c28-4046-99af-c97da7887628)

## Deadline
28.05.2024

## Notes
You can also implement your ideas, any useful information in README.md is highly encouraged!

**Comment by Corgam** [comment]
Done.
