### ISSUE TITLE
Getting Started with Interface

### ISSUE THREAD

**Issue by op-hub** [amosproj/amos2024ss04-building-information-enhancer#9]
## Task specs
- [ ] Getting started with the technology used
- [ ] Meet and discuss with SD colleagues
- [ ] Prepare first architecture drafts
- [ ] Prepare documentation
- [ ] Prepare Questions for PO/Industry partner
